// import { FoodItem } from "@/types/food.types";

// export const FOOD_ITEMS: FoodItem[] = [
//   {
//     id: "1",
//     name: "Chicken Burger",
//     restaurantName: "Burger House",
//     restaurantId: "r1",
//     price: 180,
//     rating: 4.8,
//     reviewCount: 124,
//     category: "Burger",
//     image:
//       "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
//     description:
//       "Juicy grilled chicken breast topped with crisp lettuce, tomato, and our signature mayo sauce, served in a toasted brioche bun.",
//     prepTimeMinutes: 15,
//     calories: 540,
//     ingredients: [
//       "Chicken breast",
//       "Brioche bun",
//       "Lettuce",
//       "Tomato",
//       "Mayo sauce",
//       "Onion",
//     ],
//     reviews: [
//       {
//         id: "rv1",
//         reviewerName: "Rafiq Hasan",
//         rating: 5,
//         comment: "Best burger in town, juicy and fresh!",
//         date: "2026-06-10",
//       },
//       {
//         id: "rv2",
//         reviewerName: "Nusrat Jahan",
//         rating: 4,
//         comment: "Really good but a bit pricey.",
//         date: "2026-06-05",
//       },
//       {
//         id: "rv3",
//         reviewerName: "Tanvir Ahmed",
//         rating: 5,
//         comment: "Ordered twice this week already.",
//         date: "2026-05-28",
//       },
//     ],
//   },
//   {
//     id: "2",
//     name: "Pepperoni Pizza",
//     restaurantName: "Pizza Palace",
//     restaurantId: "r2",
//     price: 350,
//     rating: 4.9,
//     reviewCount: 210,
//     category: "Pizza",
//     image:
//       "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&q=80",
//     description:
//       "Classic Italian-style pizza loaded with spicy pepperoni, mozzarella cheese, and our homemade tomato sauce on a thin crispy crust.",
//     prepTimeMinutes: 25,
//     calories: 820,
//     ingredients: [
//       "Pizza dough",
//       "Pepperoni",
//       "Mozzarella",
//       "Tomato sauce",
//       "Oregano",
//     ],
//     reviews: [
//       {
//         id: "rv4",
//         reviewerName: "Sadia Islam",
//         rating: 5,
//         comment: "Authentic taste, crust is perfect.",
//         date: "2026-06-12",
//       },
//       {
//         id: "rv5",
//         reviewerName: "Imran Khan",
//         rating: 5,
//         comment: "Family favorite, never disappoints.",
//         date: "2026-06-01",
//       },
//       {
//         id: "rv6",
//         reviewerName: "Farzana Akter",
//         rating: 4,
//         comment: "Great pizza, delivery took a bit long.",
//         date: "2026-05-20",
//       },
//     ],
//   },
//   {
//     id: "3",
//     name: "Beef Fried Rice",
//     restaurantName: "Rice & Spice",
//     restaurantId: "r3",
//     price: 220,
//     rating: 4.7,
//     reviewCount: 98,
//     category: "Rice",
//     image:
//       "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
//     description:
//       "Wok-fried rice tossed with tender beef strips, scrambled egg, and fresh vegetables in a savory soy-garlic sauce.",
//     prepTimeMinutes: 20,
//     calories: 610,
//     ingredients: [
//       "Rice",
//       "Beef strips",
//       "Egg",
//       "Carrot",
//       "Spring onion",
//       "Soy sauce",
//     ],
//     reviews: [
//       {
//         id: "rv7",
//         reviewerName: "Mahin Rahman",
//         rating: 5,
//         comment: "Flavor packed, generous beef portion.",
//         date: "2026-06-08",
//       },
//       {
//         id: "rv8",
//         reviewerName: "Lamia Chowdhury",
//         rating: 4,
//         comment: "Good but a little oily for my taste.",
//         date: "2026-05-30",
//       },
//       {
//         id: "rv9",
//         reviewerName: "Sajid Hossain",
//         rating: 5,
//         comment: "My go-to lunch order.",
//         date: "2026-05-15",
//       },
//     ],
//   },
//   {
//     id: "4",
//     name: "Mango Lassi",
//     restaurantName: "Sweet Dreams",
//     restaurantId: "r4",
//     price: 90,
//     rating: 4.6,
//     reviewCount: 76,
//     category: "Drinks",
//     image:
//       "https://images.unsplash.com/photo-1571805341302-77f3a6c69cd6?w=600&q=80",
//     description:
//       "Refreshing yogurt-based drink blended with ripe mango pulp, a touch of cardamom, and a hint of honey.",
//     prepTimeMinutes: 5,
//     calories: 220,
//     ingredients: ["Yogurt", "Mango pulp", "Honey", "Cardamom", "Ice"],
//     reviews: [
//       {
//         id: "rv10",
//         reviewerName: "Tasnim Akter",
//         rating: 5,
//         comment: "So refreshing on a hot day!",
//         date: "2026-06-15",
//       },
//       {
//         id: "rv11",
//         reviewerName: "Rakib Hasan",
//         rating: 4,
//         comment: "Could use a bit more mango flavor.",
//         date: "2026-06-02",
//       },
//     ],
//   },
//   {
//     id: "5",
//     name: "Chocolate Cake",
//     restaurantName: "Sweet Dreams",
//     restaurantId: "r4",
//     price: 150,
//     rating: 4.9,
//     reviewCount: 152,
//     category: "Dessert",
//     image:
//       "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80",
//     description:
//       "Rich layered chocolate cake with smooth ganache frosting, made fresh daily with premium cocoa.",
//     prepTimeMinutes: 10,
//     calories: 480,
//     ingredients: ["Cocoa", "Flour", "Butter", "Sugar", "Eggs", "Ganache"],
//     reviews: [
//       {
//         id: "rv12",
//         reviewerName: "Nadia Sultana",
//         rating: 5,
//         comment: "Decadent and not too sweet, perfect!",
//         date: "2026-06-11",
//       },
//       {
//         id: "rv13",
//         reviewerName: "Arif Hossain",
//         rating: 5,
//         comment: "Best chocolate cake I've had in Dhaka.",
//         date: "2026-06-03",
//       },
//     ],
//   },
//   {
//     id: "6",
//     name: "Grilled Chicken",
//     restaurantName: "Burger House",
//     restaurantId: "r1",
//     price: 280,
//     rating: 4.8,
//     reviewCount: 134,
//     category: "Chicken",
//     image:
//       "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&q=80",
//     description:
//       "Marinated chicken thighs grilled to perfection, served with garlic butter sauce and roasted vegetables.",
//     prepTimeMinutes: 22,
//     calories: 590,
//     ingredients: [
//       "Chicken thigh",
//       "Garlic butter",
//       "Bell pepper",
//       "Zucchini",
//       "Herbs",
//     ],
//     reviews: [
//       {
//         id: "rv14",
//         reviewerName: "Sumaiya Khan",
//         rating: 5,
//         comment: "Perfectly grilled, juicy every time.",
//         date: "2026-06-09",
//       },
//       {
//         id: "rv15",
//         reviewerName: "Tarek Aziz",
//         rating: 4,
//         comment: "Great taste, portion could be bigger.",
//         date: "2026-05-25",
//       },
//     ],
//   },
//   {
//     id: "7",
//     name: "Veggie Pizza",
//     restaurantName: "Pizza Palace",
//     restaurantId: "r2",
//     price: 300,
//     rating: 4.5,
//     reviewCount: 88,
//     category: "Pizza",
//     image:
//       "https://images.unsplash.com/photo-1511689660979-10d2b1aada49?w=600&q=80",
//     description:
//       "Loaded with bell peppers, mushrooms, onions, olives, and mozzarella cheese on our classic hand-tossed crust.",
//     prepTimeMinutes: 25,
//     calories: 680,
//     ingredients: [
//       "Pizza dough",
//       "Bell pepper",
//       "Mushroom",
//       "Onion",
//       "Olives",
//       "Mozzarella",
//     ],
//     reviews: [
//       {
//         id: "rv16",
//         reviewerName: "Mim Akter",
//         rating: 5,
//         comment: "Loaded with fresh veggies, love it.",
//         date: "2026-06-07",
//       },
//       {
//         id: "rv17",
//         reviewerName: "Naim Islam",
//         rating: 4,
//         comment: "Good vegetarian option.",
//         date: "2026-05-18",
//       },
//     ],
//   },
//   {
//     id: "8",
//     name: "Lemon Tea",
//     restaurantName: "Sweet Dreams",
//     restaurantId: "r4",
//     price: 60,
//     rating: 4.7,
//     reviewCount: 64,
//     category: "Drinks",
//     image:
//       "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80",
//     description:
//       "Hot brewed tea infused with fresh lemon and a touch of honey, perfect for any time of day.",
//     prepTimeMinutes: 5,
//     calories: 60,
//     ingredients: ["Black tea", "Lemon", "Honey"],
//     reviews: [
//       {
//         id: "rv18",
//         reviewerName: "Joya Akter",
//         rating: 5,
//         comment: "Simple and refreshing.",
//         date: "2026-06-14",
//       },
//       {
//         id: "rv19",
//         reviewerName: "Shakil Ahmed",
//         rating: 4,
//         comment: "Good but wish it was bigger size.",
//         date: "2026-06-01",
//       },
//     ],
//   },
//   {
//     id: "9",
//     name: "Classic Cheeseburger",
//     restaurantName: "Burger House",
//     restaurantId: "r1",
//     price: 200,
//     rating: 4.6,
//     reviewCount: 102,
//     category: "Burger",
//     image:
//       "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&q=80",
//     description:
//       "Beef patty topped with melted cheddar cheese, pickles, onions, and our house special sauce.",
//     prepTimeMinutes: 15,
//     calories: 610,
//     ingredients: [
//       "Beef patty",
//       "Cheddar cheese",
//       "Pickles",
//       "Onion",
//       "House sauce",
//       "Bun",
//     ],
//     reviews: [
//       {
//         id: "rv20",
//         reviewerName: "Riad Hossain",
//         rating: 5,
//         comment: "Classic done right.",
//         date: "2026-06-06",
//       },
//       {
//         id: "rv21",
//         reviewerName: "Sabrina Yasmin",
//         rating: 4,
//         comment: "Tasty, generous cheese.",
//         date: "2026-05-22",
//       },
//     ],
//   },
//   {
//     id: "10",
//     name: "Margherita Pizza",
//     restaurantName: "Pizza Palace",
//     restaurantId: "r2",
//     price: 280,
//     rating: 4.7,
//     reviewCount: 95,
//     category: "Pizza",
//     image:
//       "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&q=80",
//     description:
//       "Simple and authentic with San Marzano tomatoes, fresh mozzarella, and basil leaves on a thin crust.",
//     prepTimeMinutes: 20,
//     calories: 590,
//     ingredients: [
//       "Pizza dough",
//       "Tomato",
//       "Fresh mozzarella",
//       "Basil",
//       "Olive oil",
//     ],
//     reviews: [
//       {
//         id: "rv22",
//         reviewerName: "Hridoy Islam",
//         rating: 5,
//         comment: "Authentic Italian flavor.",
//         date: "2026-06-04",
//       },
//       {
//         id: "rv23",
//         reviewerName: "Promi Rahman",
//         rating: 4,
//         comment: "Simple but delicious.",
//         date: "2026-05-29",
//       },
//     ],
//   },
//   {
//     id: "11",
//     name: "Chicken Fried Rice",
//     restaurantName: "Rice & Spice",
//     restaurantId: "r3",
//     price: 190,
//     rating: 4.5,
//     reviewCount: 71,
//     category: "Rice",
//     image:
//       "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80",
//     description:
//       "Classic fried rice with tender chicken pieces, mixed vegetables, and a savory soy-based seasoning.",
//     prepTimeMinutes: 18,
//     calories: 560,
//     ingredients: ["Rice", "Chicken", "Carrot", "Peas", "Soy sauce", "Egg"],
//     reviews: [
//       {
//         id: "rv24",
//         reviewerName: "Anika Tabassum",
//         rating: 4,
//         comment: "Good portion size, tasty.",
//         date: "2026-06-02",
//       },
//       {
//         id: "rv25",
//         reviewerName: "Fahim Reza",
//         rating: 5,
//         comment: "My favorite comfort food.",
//         date: "2026-05-19",
//       },
//     ],
//   },
//   {
//     id: "12",
//     name: "Spicy Wings",
//     restaurantName: "Burger House",
//     restaurantId: "r1",
//     price: 240,
//     rating: 4.8,
//     reviewCount: 118,
//     category: "Chicken",
//     image:
//       "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&q=80",
//     description:
//       "Crispy chicken wings tossed in our signature spicy buffalo sauce, served with celery sticks and ranch dip.",
//     prepTimeMinutes: 20,
//     calories: 520,
//     ingredients: ["Chicken wings", "Buffalo sauce", "Celery", "Ranch dip"],
//     reviews: [
//       {
//         id: "rv26",
//         reviewerName: "Mehedi Hasan",
//         rating: 5,
//         comment: "Perfectly spicy, very crispy.",
//         date: "2026-06-13",
//       },
//       {
//         id: "rv27",
//         reviewerName: "Sharmin Akter",
//         rating: 4,
//         comment: "Good heat level, not overpowering.",
//         date: "2026-05-27",
//       },
//     ],
//   },
//   {
//     id: "13",
//     name: "Vanilla Ice Cream Sundae",
//     restaurantName: "Sweet Dreams",
//     restaurantId: "r4",
//     price: 130,
//     rating: 4.8,
//     reviewCount: 89,
//     category: "Dessert",
//     image:
//       "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&q=80",
//     description:
//       "Creamy vanilla ice cream topped with chocolate syrup, whipped cream, and crushed nuts.",
//     prepTimeMinutes: 8,
//     calories: 410,
//     ingredients: [
//       "Vanilla ice cream",
//       "Chocolate syrup",
//       "Whipped cream",
//       "Nuts",
//     ],
//     reviews: [
//       {
//         id: "rv28",
//         reviewerName: "Tania Sultana",
//         rating: 5,
//         comment: "Perfect dessert after dinner.",
//         date: "2026-06-10",
//       },
//       {
//         id: "rv29",
//         reviewerName: "Omar Faruk",
//         rating: 4,
//         comment: "Generous toppings, very tasty.",
//         date: "2026-05-24",
//       },
//     ],
//   },
//   {
//     id: "14",
//     name: "Iced Coffee",
//     restaurantName: "Sweet Dreams",
//     restaurantId: "r4",
//     price: 110,
//     rating: 4.6,
//     reviewCount: 67,
//     category: "Drinks",
//     image:
//       "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&q=80",
//     description:
//       "Smooth cold brew coffee served over ice with a splash of milk, lightly sweetened.",
//     prepTimeMinutes: 5,
//     calories: 140,
//     ingredients: ["Cold brew coffee", "Milk", "Sugar", "Ice"],
//     reviews: [
//       {
//         id: "rv30",
//         reviewerName: "Sabbir Ahmed",
//         rating: 5,
//         comment: "Strong and smooth, great pick-me-up.",
//         date: "2026-06-09",
//       },
//       {
//         id: "rv31",
//         reviewerName: "Nusaiba Haque",
//         rating: 4,
//         comment: "Good but a bit too sweet for me.",
//         date: "2026-05-21",
//       },
//     ],
//   },
//   {
//     id: "15",
//     name: "BBQ Chicken Burger",
//     restaurantName: "Burger House",
//     restaurantId: "r1",
//     price: 210,
//     rating: 4.7,
//     reviewCount: 93,
//     category: "Burger",
//     image:
//       "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&q=80",
//     description:
//       "Grilled chicken patty smothered in smoky BBQ sauce, topped with crispy onion rings and cheddar cheese.",
//     prepTimeMinutes: 16,
//     calories: 650,
//     ingredients: [
//       "Chicken patty",
//       "BBQ sauce",
//       "Onion rings",
//       "Cheddar cheese",
//       "Bun",
//     ],
//     reviews: [
//       {
//         id: "rv32",
//         reviewerName: "Jannatul Ferdous",
//         rating: 5,
//         comment: "Smoky and delicious, loved it!",
//         date: "2026-06-12",
//       },
//       {
//         id: "rv33",
//         reviewerName: "Rezaul Karim",
//         rating: 4,
//         comment: "Great combo of flavors.",
//         date: "2026-05-26",
//       },
//     ],
//   },
//   {
//     id: "16",
//     name: "Chicken Biryani",
//     restaurantName: "Rice & Spice",
//     restaurantId: "r3",
//     price: 250,
//     rating: 4.9,
//     reviewCount: 187,
//     category: "Rice",
//     image:
//       "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&q=80",
//     description:
//       "Fragrant basmati rice layered with spiced chicken, fried onions, and traditional biryani spices.",
//     prepTimeMinutes: 30,
//     calories: 720,
//     ingredients: [
//       "Basmati rice",
//       "Chicken",
//       "Fried onion",
//       "Biryani spices",
//       "Saffron",
//     ],
//     reviews: [
//       {
//         id: "rv34",
//         reviewerName: "Shahriar Kabir",
//         rating: 5,
//         comment: "Authentic taste, perfectly spiced.",
//         date: "2026-06-15",
//       },
//       {
//         id: "rv35",
//         reviewerName: "Rumana Begum",
//         rating: 5,
//         comment: "Best biryani I've ordered online.",
//         date: "2026-06-08",
//       },
//     ],
//   },
// ];

// export function getFoodById(id: string): FoodItem | undefined {
//   return FOOD_ITEMS.find((item) => item.id === id);
// }

// export function getRelatedFoods(
//   category: string,
//   excludeId: string,
//   count = 4,
// ): FoodItem[] {
//   return FOOD_ITEMS.filter(
//     (item) => item.category === category && item.id !== excludeId,
//   ).slice(0, count);
// }

// 2
import { FoodItem } from "@/types/food.types";
// Prices below are in USD ($)

export const FOOD_ITEMS: FoodItem[] = [
  {
    id: "1",
    name: "Chicken Burger",
    restaurantName: "Burger House",
    restaurantId: "r1",
    price: 4.99,
    rating: 4.8,
    reviewCount: 124,
    category: "Burger",
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    description:
      "Juicy grilled chicken breast topped with crisp lettuce, tomato, and our signature mayo sauce, served in a toasted brioche bun.",
    prepTimeMinutes: 15,
    calories: 540,
    ingredients: [
      "Chicken breast",
      "Brioche bun",
      "Lettuce",
      "Tomato",
      "Mayo sauce",
      "Onion",
    ],
    reviews: [
      {
        id: "rv1",
        reviewerName: "Rafiq Hasan",
        rating: 5,
        comment: "Best burger in town, juicy and fresh!",
        date: "2026-06-10",
      },
      {
        id: "rv2",
        reviewerName: "Nusrat Jahan",
        rating: 4,
        comment: "Really good but a bit pricey.",
        date: "2026-06-05",
      },
      {
        id: "rv3",
        reviewerName: "Tanvir Ahmed",
        rating: 5,
        comment: "Ordered twice this week already.",
        date: "2026-05-28",
      },
    ],
  },
  {
    id: "2",
    name: "Pepperoni Pizza",
    restaurantName: "Pizza Palace",
    restaurantId: "r2",
    price: 9.99,
    rating: 4.9,
    reviewCount: 210,
    category: "Pizza",
    image:
      "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&q=80",
    description:
      "Classic Italian-style pizza loaded with spicy pepperoni, mozzarella cheese, and our homemade tomato sauce on a thin crispy crust.",
    prepTimeMinutes: 25,
    calories: 820,
    ingredients: [
      "Pizza dough",
      "Pepperoni",
      "Mozzarella",
      "Tomato sauce",
      "Oregano",
    ],
    reviews: [
      {
        id: "rv4",
        reviewerName: "Sadia Islam",
        rating: 5,
        comment: "Authentic taste, crust is perfect.",
        date: "2026-06-12",
      },
      {
        id: "rv5",
        reviewerName: "Imran Khan",
        rating: 5,
        comment: "Family favorite, never disappoints.",
        date: "2026-06-01",
      },
      {
        id: "rv6",
        reviewerName: "Farzana Akter",
        rating: 4,
        comment: "Great pizza, delivery took a bit long.",
        date: "2026-05-20",
      },
    ],
  },
  {
    id: "3",
    name: "Beef Fried Rice",
    restaurantName: "Rice & Spice",
    restaurantId: "r3",
    price: 6.49,
    rating: 4.7,
    reviewCount: 98,
    category: "Rice",
    image:
      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
    description:
      "Wok-fried rice tossed with tender beef strips, scrambled egg, and fresh vegetables in a savory soy-garlic sauce.",
    prepTimeMinutes: 20,
    calories: 610,
    ingredients: [
      "Rice",
      "Beef strips",
      "Egg",
      "Carrot",
      "Spring onion",
      "Soy sauce",
    ],
    reviews: [
      {
        id: "rv7",
        reviewerName: "Mahin Rahman",
        rating: 5,
        comment: "Flavor packed, generous beef portion.",
        date: "2026-06-08",
      },
      {
        id: "rv8",
        reviewerName: "Lamia Chowdhury",
        rating: 4,
        comment: "Good but a little oily for my taste.",
        date: "2026-05-30",
      },
      {
        id: "rv9",
        reviewerName: "Sajid Hossain",
        rating: 5,
        comment: "My go-to lunch order.",
        date: "2026-05-15",
      },
    ],
  },
  {
    id: "4",
    name: "Mango Lassi",
    restaurantName: "Sweet Dreams",
    restaurantId: "r4",
    price: 2.99,
    rating: 4.6,
    reviewCount: 76,
    category: "Drinks",
    image:
      "https://images.unsplash.com/photo-1571805341302-77f3a6c69cd6?w=600&q=80",
    description:
      "Refreshing yogurt-based drink blended with ripe mango pulp, a touch of cardamom, and a hint of honey.",
    prepTimeMinutes: 5,
    calories: 220,
    ingredients: ["Yogurt", "Mango pulp", "Honey", "Cardamom", "Ice"],
    reviews: [
      {
        id: "rv10",
        reviewerName: "Tasnim Akter",
        rating: 5,
        comment: "So refreshing on a hot day!",
        date: "2026-06-15",
      },
      {
        id: "rv11",
        reviewerName: "Rakib Hasan",
        rating: 4,
        comment: "Could use a bit more mango flavor.",
        date: "2026-06-02",
      },
    ],
  },
  {
    id: "5",
    name: "Chocolate Cake",
    restaurantName: "Sweet Dreams",
    restaurantId: "r4",
    price: 4.49,
    rating: 4.9,
    reviewCount: 152,
    category: "Dessert",
    image:
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80",
    description:
      "Rich layered chocolate cake with smooth ganache frosting, made fresh daily with premium cocoa.",
    prepTimeMinutes: 10,
    calories: 480,
    ingredients: ["Cocoa", "Flour", "Butter", "Sugar", "Eggs", "Ganache"],
    reviews: [
      {
        id: "rv12",
        reviewerName: "Nadia Sultana",
        rating: 5,
        comment: "Decadent and not too sweet, perfect!",
        date: "2026-06-11",
      },
      {
        id: "rv13",
        reviewerName: "Arif Hossain",
        rating: 5,
        comment: "Best chocolate cake I've had in Dhaka.",
        date: "2026-06-03",
      },
    ],
  },
  {
    id: "6",
    name: "Grilled Chicken",
    restaurantName: "Burger House",
    restaurantId: "r1",
    price: 7.99,
    rating: 4.8,
    reviewCount: 134,
    category: "Chicken",
    image:
      "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&q=80",
    description:
      "Marinated chicken thighs grilled to perfection, served with garlic butter sauce and roasted vegetables.",
    prepTimeMinutes: 22,
    calories: 590,
    ingredients: [
      "Chicken thigh",
      "Garlic butter",
      "Bell pepper",
      "Zucchini",
      "Herbs",
    ],
    reviews: [
      {
        id: "rv14",
        reviewerName: "Sumaiya Khan",
        rating: 5,
        comment: "Perfectly grilled, juicy every time.",
        date: "2026-06-09",
      },
      {
        id: "rv15",
        reviewerName: "Tarek Aziz",
        rating: 4,
        comment: "Great taste, portion could be bigger.",
        date: "2026-05-25",
      },
    ],
  },
  {
    id: "7",
    name: "Veggie Pizza",
    restaurantName: "Pizza Palace",
    restaurantId: "r2",
    price: 8.49,
    rating: 4.5,
    reviewCount: 88,
    category: "Pizza",
    image:
      "https://images.unsplash.com/photo-1511689660979-10d2b1aada49?w=600&q=80",
    description:
      "Loaded with bell peppers, mushrooms, onions, olives, and mozzarella cheese on our classic hand-tossed crust.",
    prepTimeMinutes: 25,
    calories: 680,
    ingredients: [
      "Pizza dough",
      "Bell pepper",
      "Mushroom",
      "Onion",
      "Olives",
      "Mozzarella",
    ],
    reviews: [
      {
        id: "rv16",
        reviewerName: "Mim Akter",
        rating: 5,
        comment: "Loaded with fresh veggies, love it.",
        date: "2026-06-07",
      },
      {
        id: "rv17",
        reviewerName: "Naim Islam",
        rating: 4,
        comment: "Good vegetarian option.",
        date: "2026-05-18",
      },
    ],
  },
  {
    id: "8",
    name: "Lemon Tea",
    restaurantName: "Sweet Dreams",
    restaurantId: "r4",
    price: 1.99,
    rating: 4.7,
    reviewCount: 64,
    category: "Drinks",
    image:
      "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80",
    description:
      "Hot brewed tea infused with fresh lemon and a touch of honey, perfect for any time of day.",
    prepTimeMinutes: 5,
    calories: 60,
    ingredients: ["Black tea", "Lemon", "Honey"],
    reviews: [
      {
        id: "rv18",
        reviewerName: "Joya Akter",
        rating: 5,
        comment: "Simple and refreshing.",
        date: "2026-06-14",
      },
      {
        id: "rv19",
        reviewerName: "Shakil Ahmed",
        rating: 4,
        comment: "Good but wish it was bigger size.",
        date: "2026-06-01",
      },
    ],
  },
  {
    id: "9",
    name: "Classic Cheeseburger",
    restaurantName: "Burger House",
    restaurantId: "r1",
    price: 5.99,
    rating: 4.6,
    reviewCount: 102,
    category: "Burger",
    image:
      "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&q=80",
    description:
      "Beef patty topped with melted cheddar cheese, pickles, onions, and our house special sauce.",
    prepTimeMinutes: 15,
    calories: 610,
    ingredients: [
      "Beef patty",
      "Cheddar cheese",
      "Pickles",
      "Onion",
      "House sauce",
      "Bun",
    ],
    reviews: [
      {
        id: "rv20",
        reviewerName: "Riad Hossain",
        rating: 5,
        comment: "Classic done right.",
        date: "2026-06-06",
      },
      {
        id: "rv21",
        reviewerName: "Sabrina Yasmin",
        rating: 4,
        comment: "Tasty, generous cheese.",
        date: "2026-05-22",
      },
    ],
  },
  {
    id: "10",
    name: "Margherita Pizza",
    restaurantName: "Pizza Palace",
    restaurantId: "r2",
    price: 7.99,
    rating: 4.7,
    reviewCount: 95,
    category: "Pizza",
    image:
      "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&q=80",
    description:
      "Simple and authentic with San Marzano tomatoes, fresh mozzarella, and basil leaves on a thin crust.",
    prepTimeMinutes: 20,
    calories: 590,
    ingredients: [
      "Pizza dough",
      "Tomato",
      "Fresh mozzarella",
      "Basil",
      "Olive oil",
    ],
    reviews: [
      {
        id: "rv22",
        reviewerName: "Hridoy Islam",
        rating: 5,
        comment: "Authentic Italian flavor.",
        date: "2026-06-04",
      },
      {
        id: "rv23",
        reviewerName: "Promi Rahman",
        rating: 4,
        comment: "Simple but delicious.",
        date: "2026-05-29",
      },
    ],
  },
  {
    id: "11",
    name: "Chicken Fried Rice",
    restaurantName: "Rice & Spice",
    restaurantId: "r3",
    price: 5.49,
    rating: 4.5,
    reviewCount: 71,
    category: "Rice",
    image:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80",
    description:
      "Classic fried rice with tender chicken pieces, mixed vegetables, and a savory soy-based seasoning.",
    prepTimeMinutes: 18,
    calories: 560,
    ingredients: ["Rice", "Chicken", "Carrot", "Peas", "Soy sauce", "Egg"],
    reviews: [
      {
        id: "rv24",
        reviewerName: "Anika Tabassum",
        rating: 4,
        comment: "Good portion size, tasty.",
        date: "2026-06-02",
      },
      {
        id: "rv25",
        reviewerName: "Fahim Reza",
        rating: 5,
        comment: "My favorite comfort food.",
        date: "2026-05-19",
      },
    ],
  },
  {
    id: "12",
    name: "Spicy Wings",
    restaurantName: "Burger House",
    restaurantId: "r1",
    price: 6.99,
    rating: 4.8,
    reviewCount: 118,
    category: "Chicken",
    image:
      "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&q=80",
    description:
      "Crispy chicken wings tossed in our signature spicy buffalo sauce, served with celery sticks and ranch dip.",
    prepTimeMinutes: 20,
    calories: 520,
    ingredients: ["Chicken wings", "Buffalo sauce", "Celery", "Ranch dip"],
    reviews: [
      {
        id: "rv26",
        reviewerName: "Mehedi Hasan",
        rating: 5,
        comment: "Perfectly spicy, very crispy.",
        date: "2026-06-13",
      },
      {
        id: "rv27",
        reviewerName: "Sharmin Akter",
        rating: 4,
        comment: "Good heat level, not overpowering.",
        date: "2026-05-27",
      },
    ],
  },
  {
    id: "13",
    name: "Vanilla Ice Cream Sundae",
    restaurantName: "Sweet Dreams",
    restaurantId: "r4",
    price: 3.99,
    rating: 4.8,
    reviewCount: 89,
    category: "Dessert",
    image:
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&q=80",
    description:
      "Creamy vanilla ice cream topped with chocolate syrup, whipped cream, and crushed nuts.",
    prepTimeMinutes: 8,
    calories: 410,
    ingredients: [
      "Vanilla ice cream",
      "Chocolate syrup",
      "Whipped cream",
      "Nuts",
    ],
    reviews: [
      {
        id: "rv28",
        reviewerName: "Tania Sultana",
        rating: 5,
        comment: "Perfect dessert after dinner.",
        date: "2026-06-10",
      },
      {
        id: "rv29",
        reviewerName: "Omar Faruk",
        rating: 4,
        comment: "Generous toppings, very tasty.",
        date: "2026-05-24",
      },
    ],
  },
  {
    id: "14",
    name: "Iced Coffee",
    restaurantName: "Sweet Dreams",
    restaurantId: "r4",
    price: 3.49,
    rating: 4.6,
    reviewCount: 67,
    category: "Drinks",
    image:
      "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&q=80",
    description:
      "Smooth cold brew coffee served over ice with a splash of milk, lightly sweetened.",
    prepTimeMinutes: 5,
    calories: 140,
    ingredients: ["Cold brew coffee", "Milk", "Sugar", "Ice"],
    reviews: [
      {
        id: "rv30",
        reviewerName: "Sabbir Ahmed",
        rating: 5,
        comment: "Strong and smooth, great pick-me-up.",
        date: "2026-06-09",
      },
      {
        id: "rv31",
        reviewerName: "Nusaiba Haque",
        rating: 4,
        comment: "Good but a bit too sweet for me.",
        date: "2026-05-21",
      },
    ],
  },
  {
    id: "15",
    name: "BBQ Chicken Burger",
    restaurantName: "Burger House",
    restaurantId: "r1",
    price: 5.99,
    rating: 4.7,
    reviewCount: 93,
    category: "Burger",
    image:
      "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&q=80",
    description:
      "Grilled chicken patty smothered in smoky BBQ sauce, topped with crispy onion rings and cheddar cheese.",
    prepTimeMinutes: 16,
    calories: 650,
    ingredients: [
      "Chicken patty",
      "BBQ sauce",
      "Onion rings",
      "Cheddar cheese",
      "Bun",
    ],
    reviews: [
      {
        id: "rv32",
        reviewerName: "Jannatul Ferdous",
        rating: 5,
        comment: "Smoky and delicious, loved it!",
        date: "2026-06-12",
      },
      {
        id: "rv33",
        reviewerName: "Rezaul Karim",
        rating: 4,
        comment: "Great combo of flavors.",
        date: "2026-05-26",
      },
    ],
  },
  {
    id: "16",
    name: "Chicken Biryani",
    restaurantName: "Rice & Spice",
    restaurantId: "r3",
    price: 6.99,
    rating: 4.9,
    reviewCount: 187,
    category: "Rice",
    image:
      "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&q=80",
    description:
      "Fragrant basmati rice layered with spiced chicken, fried onions, and traditional biryani spices.",
    prepTimeMinutes: 30,
    calories: 720,
    ingredients: [
      "Basmati rice",
      "Chicken",
      "Fried onion",
      "Biryani spices",
      "Saffron",
    ],
    reviews: [
      {
        id: "rv34",
        reviewerName: "Shahriar Kabir",
        rating: 5,
        comment: "Authentic taste, perfectly spiced.",
        date: "2026-06-15",
      },
      {
        id: "rv35",
        reviewerName: "Rumana Begum",
        rating: 5,
        comment: "Best biryani I've ordered online.",
        date: "2026-06-08",
      },
    ],
  },
];

export function getFoodById(id: string): FoodItem | undefined {
  return FOOD_ITEMS.find((item) => item.id === id);
}

export function getRelatedFoods(
  category: string,
  excludeId: string,
  count = 4,
): FoodItem[] {
  return FOOD_ITEMS.filter(
    (item) => item.category === category && item.id !== excludeId,
  ).slice(0, count);
}